export const products = [
  {
    "id": 1,
    "name": "iPhone 17 Pro Max (256GB)",
    "brand": "Apple",
    "category": "Phones",
    "price": 5099,
    "stock": "In stock",
    "badge": "Top Flagship",
    "image": "products image/iphone-17-pro-max--256gb-.jpg",
    "description": "The 2026 ultimate flagship featuring the A19 Pro chip and the new unified camera plateau design."
  },
  {
    "id": 2,
    "name": "iPhone 17 Pro (256GB)",
    "brand": "Apple",
    "category": "Phones",
    "price": 4649,
    "stock": "In stock",
    "badge": "Pro Choice",
    "image": "products image/iphone-17-pro--256gb-.jpg",
    "description": "Compact pro performance with advanced spatial video capabilities and titanium 2.0 build."
  },
  {
    "id": 3,
    "name": "iPhone 17 Air (Thin Model)",
    "brand": "Apple",
    "category": "Phones",
    "price": 4200,
    "stock": "Limited Stock",
    "badge": "Ultra Thin",
    "image": "products image/iphone-17-air--thin-model-.jpg",
    "description": "The new ultra-slim addition to the iPhone family, prioritizing design and portability."
  },
  {
    "id": 4,
    "name": "iPhone 17 (128GB)",
    "brand": "Apple",
    "category": "Phones",
    "price": 3150,
    "stock": "In stock",
    "badge": "Mainstream",
    "image": "products image/iphone-17--128gb-.jpg",
    "description": "The core iPhone experience for 2026 with a 120Hz ProMotion display now standard."
  },
  {
    "id": 5,
    "name": "iPhone 17E",
    "brand": "Apple",
    "category": "Phones",
    "price": 1850,
    "stock": "In stock",
    "badge": "Value Apple",
    "image": "products image/iphone-se--4th-gen---2026-.jpg",
    "description": "Modern full-screen design with OLED and A18 chip at an entry-level wholesale price."
  },
  {
    "id": 6,
    "name": "Samsung Galaxy S26 Ultra",
    "brand": "Samsung",
    "category": "Phones",
    "price": 3899,
    "stock": "In stock",
    "badge": "AI Powerhouse",
    "image": "products image/samsung-galaxy-s26-ultra.jpg",
    "description": "Snapdragon 8 Elite Gen 5 powered flagship with full Galaxy AI 2.0 integration."
  },
  {
    "id": 7,
    "name": "Samsung Galaxy S26+",
    "brand": "Samsung",
    "category": "Phones",
    "price": 3100,
    "stock": "In stock",
    "badge": "Versatile",
    "image": "products image/samsung-galaxy-s26-.jpg",
    "description": "Large display and enhanced thermal management for long-term retail value."
  },
  {
    "id": 8,
    "name": "Samsung Galaxy S26 (Standard)",
    "brand": "Samsung",
    "category": "Phones",
    "price": 2750,
    "stock": "In stock",
    "badge": "Compact Flagship",
    "image": "products image/samsung-galaxy-s26--standard-.jpg",
    "description": "The refined compact flagship with the new Exynos 2600 AI processor."
  },
  {
    "id": 9,
    "name": "Samsung Galaxy Z Fold 8",
    "brand": "Samsung",
    "category": "Phones",
    "price": 5400,
    "stock": "Limited Stock",
    "badge": "Elite Foldable",
    "image": "products image/samsung-galaxy-z-fold-8.jpg",
    "description": "Thinner, lighter, and now including an integrated S-Pen slot."
  },
  {
    "id": 10,
    "name": "Samsung Galaxy Z Flip 8",
    "brand": "Samsung",
    "category": "Phones",
    "price": 2950,
    "stock": "In stock",
    "badge": "Fashion Tech",
    "image": "products image/samsung-galaxy-z-flip-8.jpg",
    "description": "Redesigned outer screen that covers the entire front panel when folded."
  },
  {
    "id": 11,
    "name": "Google Pixel 10 Pro XL",
    "brand": "Google",
    "category": "Phones",
    "price": 3799,
    "stock": "In stock",
    "badge": "Editor's Choice",
    "image": "products image/google-pixel-10-pro-xl.jpg",
    "description": "Featuring the Tensor G5 chip, completely designed by Google for 2026."
  },
  {
    "id": 12,
    "name": "Google Pixel 10 Pro",
    "brand": "Google",
    "category": "Phones",
    "price": 3450,
    "stock": "In stock",
    "badge": "Compact Pro",
    "image": "products image/google-pixel-10-pro.jpg",
    "description": "Pro features in a smaller form factor with the best software experience in 2026."
  },
  {
    "id": 13,
    "name": "Google Pixel 10 (Standard)",
    "brand": "Google",
    "category": "Phones",
    "price": 2650,
    "stock": "In stock",
    "badge": "AI First",
    "image": "",
    "description": "The most balanced Android flagship for everyday users and bulk retail."
  },
  {
    "id": 14,
    "name": "Google Pixel 10 Pro Fold",
    "brand": "Google",
    "category": "Phones",
    "price": 4950,
    "stock": "Limited Stock",
    "badge": "Premium Fold",
    "image": "products image/google-pixel-10-pro-fold.jpg",
    "description": "Google's ultra-premium foldable with enhanced durability and AI multi-tasking."
  },
  {
    "id": 15,
    "name": "Google Pixel 10a",
    "brand": "Google",
    "category": "Phones",
    "price": 1650,
    "stock": "In stock",
    "badge": "Volume King",
    "image": "products image/google-pixel-10a.jpg",
    "description": "The highest value camera system in the budget-premium wholesale market."
  },
  {
    "id": 16,
    "name": "Xiaomi 17 Ultra",
    "brand": "Xiaomi",
    "category": "Phones",
    "price": 4450,
    "stock": "In stock",
    "badge": "Optics Leader",
    "image": "products image/xiaomi-17-ultra.jpg",
    "description": "1-inch sensor professional optics co-engineered with Leica for 2026."
  },
  {
    "id": 17,
    "name": "Xiaomi 17 Pro",
    "brand": "Xiaomi",
    "category": "Phones",
    "price": 3850,
    "stock": "In stock",
    "badge": "Powerhouse",
    "image": "products image/xiaomi-17-pro.jpg",
    "description": "HyperCharge 3.0 technology allowing 0-100% charging in under 10 minutes."
  },
  {
    "id": 18,
    "name": "OnePlus 15",
    "brand": "OnePlus",
    "category": "Phones",
    "price": 2849,
    "stock": "In stock",
    "badge": "Speed King",
    "image": "products image/oneplus-15.jpg",
    "description": "The fastest performing Android device of 2026 with a massive 7000mAh battery."
  },
  {
    "id": 19,
    "name": "Nothing Phone (3)",
    "brand": "Nothing",
    "category": "Phones",
    "price": 2150,
    "stock": "In stock",
    "badge": "Design Icon",
    "image": "products image/nothing-phone--3-.jpg",
    "description": "Advanced Glyph Matrix 2.0 with deeper Nothing OS 4.0 integration."
  },
  {
    "id": 20,
    "name": "Nothing Phone (4a) Pro",
    "brand": "Nothing",
    "category": "Phones",
    "price": 1450,
    "stock": "In stock",
    "badge": "Style Value",
    "image": "products image/nothing-phone--4a--pro.jpg",
    "description": "Premium mid-range build with the signature Nothing aesthetic."
  },
  {
    "id": 21,
    "name": "AirPods Pro (3rd Gen)",
    "brand": "Apple",
    "category": "Earphones",
    "price": 890,
    "stock": "In stock",
    "badge": "Audio Gold",
    "image": "products image/airpods-pro--3rd-gen-.jpg",
    "description": "2026 upgrade with double the ANC power and new health sensors."
  },
  {
    "id": 22,
    "name": "AirPods (4th Gen)",
    "brand": "Apple",
    "category": "Earphones",
    "price": 540,
    "stock": "In stock",
    "badge": "High Demand",
    "image": "products image/airpods--4th-gen-.jpg",
    "description": "The new standard for everyday wireless audio with a smaller case."
  },
  {
    "id": 23,
    "name": "Sony WF-1000XM6",
    "brand": "Sony",
    "category": "Earphones",
    "price": 990,
    "stock": "In stock",
    "badge": "ANC King",
    "image": "products image/sony-wf-1000xm6.jpg",
    "description": "The absolute benchmark for noise cancellation in 2026."
  },
  {
    "id": 24,
    "name": "Sony WH-1000XM6",
    "brand": "Sony",
    "category": "Earphones",
    "price": 1250,
    "stock": "In stock",
    "badge": "Top Over-Ear",
    "image": "products image/sony-wh-1000xm6.jpg",
    "description": "New carbon-fiber build for the lightest pro headphones Sony has ever made."
  },
  {
    "id": 25,
    "name": "Samsung Galaxy Buds 3 Pro (2026)",
    "brand": "Samsung",
    "category": "Earphones",
    "price": 720,
    "stock": "In stock",
    "badge": "AI Enhanced",
    "image": "products image/samsung-galaxy-buds-3-pro--2026-.jpg",
    "description": "Real-time AI voice translation directly in your ears."
  },
  {
    "id": 26,
    "name": "Bose QuietComfort Ultra II",
    "brand": "Bose",
    "category": "Earphones",
    "price": 1050,
    "stock": "In stock",
    "badge": "Silent Choice",
    "image": "products image/bose-quietcomfort-ultra-ii.jpg",
    "description": "Unrivaled comfort with the 2nd Gen Immersive Audio system."
  },
  {
    "id": 27,
    "name": "Technics EAH-AZ100",
    "brand": "Technics",
    "category": "Earphones",
    "price": 1100,
    "stock": "In stock",
    "badge": "Audiophile",
    "image": "products image/technics-eah-az100.jpg",
    "description": "Premium 2026 wireless setup with triple-point Bluetooth connectivity."
  },
  {
    "id": 28,
    "name": "Nothing Ear (3)",
    "brand": "Nothing",
    "category": "Earphones",
    "price": 450,
    "stock": "In stock",
    "badge": "Style Leader",
    "image": "products image/nothing-ear--3-.jpg",
    "description": "The refined transparent audio experience for the Nothing ecosystem."
  },
  {
    "id": 29,
    "name": "ASUS ROG Phone 10",
    "brand": "ASUS",
    "category": "Phones",
    "price": 4550,
    "stock": "In stock",
    "badge": "Gaming Elite",
    "image": "products image/asus-rog-phone-10.jpg",
    "description": "240Hz refresh rate and dedicated vapor chamber for 2026 mobile gaming."
  },
  {
    "id": 30,
    "name": "Huawei P80 Ultra",
    "brand": "Huawei",
    "category": "Phones",
    "price": 4200,
    "stock": "In stock",
    "badge": "Optics Master",
    "image": "products image/huawei-p80-ultra.jpg",
    "description": "Revolutionary zoom tech with the new XMAGE 3.0 imaging system."
  },
  {
    "id": 31,
    "name": "OnePlus Buds 4 Pro",
    "brand": "OnePlus",
    "category": "Earphones",
    "price": 580,
    "stock": "In stock",
    "badge": "Value Pro",
    "image": "products image/oneplus-buds-4-pro.jpg",
    "description": "Dual driver system tuned for the most energetic sound profile."
  },
  {
    "id": 32,
    "name": "JBL Tour Pro 3",
    "brand": "JBL",
    "category": "Earphones",
    "price": 780,
    "stock": "In stock",
    "badge": "Smart Case",
    "image": "products image/jbl-tour-pro-3.jpg",
    "description": "High-res touch screen on the case for full control without a phone."
  },
  {
    "id": 33,
    "name": "Beats Solo Buds 2",
    "brand": "Apple",
    "category": "Earphones",
    "price": 350,
    "stock": "In stock",
    "badge": "Sport Entry",
    "image": "products image/beats-solo-buds-2.jpg",
    "description": "Ultra-lightweight with 18 hours of continuous battery life."
  },
  {
    "id": 34,
    "name": "Sennheiser MTW 5",
    "brand": "Sennheiser",
    "category": "Earphones",
    "price": 1150,
    "stock": "In stock",
    "badge": "Premium Audio",
    "image": "products image/sennheiser-mtw-5.jpg",
    "description": "Momentum True Wireless 5 with high-fidelity lossless audio support."
  },
  {
    "id": 35,
    "name": "Sony LinkBuds S2",
    "brand": "Sony",
    "category": "Earphones",
    "price": 490,
    "stock": "In stock",
    "badge": "Compact ANC",
    "image": "products image/sony-linkbuds-s2.jpg",
    "description": "The smallest and lightest noise-cancelling earbuds on the market."
  }
];
